version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "pulse-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_DB}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - fullstack
    volumes:
      - database_postgress:/var/lib/postgresql/data

  api:
    build: .
    container_name: "pulse-api"
    environment:
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_DB: "${DB_DB}"
      DB_HOST: "${DB_HOST}"
      DB_TABLE: "${DB_TABLE}"
      DB_PORT: "${DB_PORT}"
      SSL_MODE: "${SSL_MODE}"
      JWT_SECRET: "${JWT_SECRET}"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgress:

networks:
  fullstack:
    driver: bridge
