version: "3"
dotenv: [".env"]
tasks:
  build:
    cmds:
      - go build -o app cmd/server/main.go
  test:
    cmds:
      - go test -v ./..
  lint:
    cmds:
      - golangci-lint run
  run:
    cmds:
      - docker-compose up --build   --force-recreate
  integration-test:
    # Note: .Env config vars are passed through by bash definition in the commands below. Simply importing dotenv at the top of this file is not enough.
    cmds:
      - export DB_USERNAME=$DB_USERNAME; export DB_PASSWORD=$DB_PASSWORD; export DB_TABLE=$DB_TABLE; export DB_HOST=localhost;  export DB_PORT=$DB_PORT;  export DB_DB=$DB_DB;  export SSL_MODE=$SSL_MODE; export JWT_SECRET=$JWT_SECRET; docker-compose up -d db
      - export DB_USERNAME=$DB_USERNAME; export DB_PASSWORD=$DB_PASSWORD; export DB_TABLE=$DB_TABLE; export DB_HOST=localhost;  export DB_PORT=$DB_PORT;  export DB_DB=$DB_DB;  export SSL_MODE=$SSL_MODE; export JWT_SECRET=$JWT_SECRET; go test -tags=integration -v ./...
